# Generated by Django 5.1.6 on 2025-05-10 19:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RentalProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("without_access", "Without Access"),
                            ("motorcycle_access", "Motorcycle Access"),
                            ("car_access", "Car Access"),
                            ("car_access_parking", "Car Access + Parking"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[("apartment", "Apartment"), ("house", "House")],
                        max_length=20,
                    ),
                ),
                (
                    "num_rooms",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual rent price for training data",
                        max_digits=10,
                    ),
                ),
                (
                    "apartment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("T1", "T1"),
                            ("T2", "T2"),
                            ("T3", "T3"),
                            ("T4", "T4"),
                            ("T5", "T5"),
                            ("T6", "T6"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "house_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("F1", "F1"),
                            ("F2", "F2"),
                            ("F3", "F3"),
                            ("F4", "F4"),
                            ("F5", "F5"),
                            ("F6", "F6"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("has_house_basement", models.BooleanField(default=False)),
                ("has_showers_toilets", models.BooleanField(default=False)),
                ("has_garage", models.BooleanField(default=False)),
                ("has_garden", models.BooleanField(default=False)),
                ("has_parking", models.BooleanField(default=False)),
                ("has_surveillance_system", models.BooleanField(default=False)),
                ("has_dishwasher", models.BooleanField(default=False)),
                ("has_washing_machine", models.BooleanField(default=False)),
                ("has_internet_access", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "town",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_properties",
                        to="predictor_app.town",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandForSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paper_type",
                    models.CharField(
                        choices=[
                            ("titre_propriete", "Titre de propriété"),
                            ("acte_juridique", "Acte juridique"),
                            ("plan_cadastre", "Plan cadastre"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("without_access", "Without Access"),
                            ("motorcycle_access", "Motorcycle Access"),
                            ("car_access", "Car Access"),
                            ("car_access_parking", "Car Access + Parking"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_fenced", models.BooleanField(default=False)),
                ("is_ready_to_build", models.BooleanField(default=False)),
                (
                    "area_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Area in square meters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual sale price for training data",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "town",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lands_for_sale",
                        to="predictor_app.town",
                    ),
                ),
            ],
        ),
    ]
